### ISSUE TITLE
Move stable timesync endpoints into Telraam

### ISSUE THREAD

**Issue by mcbloch** [12urenloop/monitoring#10]
Some endpoints in the timesync service are just retrieving and transforming data from Telraam. This was practical at the time to quickly change the data format and the monitoring without needing to modify and restart Telraam.

Some endpoints are now tested and integrated in the monitoring and would better be added to Telraam. They would profit from the direct database access and the more stable environment.

My initial suggestion would be to move `/team-detection-times` and `/team-lap-times`.

**Comment by NuttyShrimp** [comment]
I've been working on this. I also suggest moving `/batons` because now the detections get fetched twice from the stations. If we register monitoring as a lapper we could use it already build fetching mechanism to get our detections to update the baton statuses

**Comment by mcbloch** [comment]
I'm fine with everything being moved but as long as Telraam can't be restarted during the event the need of a second script will stay to quickly add or change data and formats. I would not remove the timesync script and the fetch code but if no endpoint in timesync is using some data we could disabled that specific fetch part.

**Comment by redfast00** [comment]
We now directly connect to a database mirror for monitoring
