### ISSUE TITLE
Qua De La Fucks

### ISSUE THREAD

**Issue by FKD13** [12urenloop/monitoring#6]
A Lot of questions with this repo:

- How Does it Work
- What is BlackBox
- Why does the timesync script do more that timesync ?!

HELLLP

TODO:

- [ ] Figure out how things are connected
- [ ] Document it a bit
- [x] Document all things timesync does, maybe consider a namechange

**Comment by mcbloch** [comment]
The readme contains quite some info on the setup. It is however slightly outdated and could use a little update.
Do you have more specific working points on the documentation after reading the readme?

Adding a diagram of how the monitoring is connected to the rest of the systems and how the data flows would already help tremendously.
